// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protein_pep_hash.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protein_pep_hash.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace peptide_hash_database {

namespace {

const ::google::protobuf::Descriptor* phd_protein_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_protein_reflection_ = NULL;
const ::google::protobuf::Descriptor* phd_peptide_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_peptide_reflection_ = NULL;
const ::google::protobuf::Descriptor* phd_parameters_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_parameters_reflection_ = NULL;
const ::google::protobuf::Descriptor* phd_header_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_header_reflection_ = NULL;
const ::google::protobuf::Descriptor* phd_peptide_mass_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_peptide_mass_reflection_ = NULL;
const ::google::protobuf::Descriptor* phd_file_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  phd_file_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protein_5fpep_5fhash_2eproto() {
  protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protein_pep_hash.proto");
  GOOGLE_CHECK(file != NULL);
  phd_protein_descriptor_ = file->message_type(0);
  static const int phd_protein_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_protein, phdpro_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_protein, phdpro_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_protein, phdpro_pepseq_),
  };
  phd_protein_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_protein_descriptor_,
      phd_protein::default_instance_,
      phd_protein_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_protein, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_protein, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_protein));
  phd_peptide_descriptor_ = file->message_type(1);
  static const int phd_peptide_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, phdpep_protein_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, phdpep_pepstart_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, phdpep_peplen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, phdpep_cleavedpep_),
  };
  phd_peptide_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_peptide_descriptor_,
      phd_peptide::default_instance_,
      phd_peptide_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_peptide));
  phd_parameters_descriptor_ = file->message_type(2);
  static const int phd_parameters_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_precut_amino_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_postcut_amino_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_prenocut_amino_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_postnocut_amino_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_missed_cleavage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, phdparam_semi_tryptic_),
  };
  phd_parameters_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_parameters_descriptor_,
      phd_parameters::default_instance_,
      phd_parameters_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_parameters, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_parameters));
  phd_header_descriptor_ = file->message_type(3);
  static const int phd_header_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_protein_source_filename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_protein_source_file_digest_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_num_proteins_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_hash_file_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_hash_file_digest_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, phdhdr_params_),
  };
  phd_header_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_header_descriptor_,
      phd_header::default_instance_,
      phd_header_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_header, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_header));
  phd_peptide_mass_descriptor_ = file->message_type(4);
  static const int phd_peptide_mass_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide_mass, phdpmass_mass_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide_mass, phdpmass_peptide_list_),
  };
  phd_peptide_mass_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_peptide_mass_descriptor_,
      phd_peptide_mass::default_instance_,
      phd_peptide_mass_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide_mass, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_peptide_mass, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_peptide_mass));
  phd_file_descriptor_ = file->message_type(5);
  static const int phd_file_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_file, phdhdr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_file, phdpro_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_file, phdpepm_),
  };
  phd_file_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      phd_file_descriptor_,
      phd_file::default_instance_,
      phd_file_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_file, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(phd_file, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(phd_file));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protein_5fpep_5fhash_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_protein_descriptor_, &phd_protein::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_peptide_descriptor_, &phd_peptide::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_parameters_descriptor_, &phd_parameters::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_header_descriptor_, &phd_header::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_peptide_mass_descriptor_, &phd_peptide_mass::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    phd_file_descriptor_, &phd_file::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protein_5fpep_5fhash_2eproto() {
  delete phd_protein::default_instance_;
  delete phd_protein_reflection_;
  delete phd_peptide::default_instance_;
  delete phd_peptide_reflection_;
  delete phd_parameters::default_instance_;
  delete phd_parameters_reflection_;
  delete phd_header::default_instance_;
  delete phd_header_reflection_;
  delete phd_peptide_mass::default_instance_;
  delete phd_peptide_mass_reflection_;
  delete phd_file::default_instance_;
  delete phd_file_reflection_;
}

void protobuf_AddDesc_protein_5fpep_5fhash_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026protein_pep_hash.proto\022\025peptide_hash_d"
    "atabase\"L\n\013phd_protein\022\023\n\013phdpro_name\030\001 "
    "\002(\t\022\021\n\tphdpro_id\030\002 \002(\005\022\025\n\rphdpro_pepseq\030"
    "\003 \002(\t\"s\n\013phd_peptide\022\031\n\021phdpep_protein_i"
    "d\030\001 \002(\005\022\027\n\017phdpep_pepstart\030\002 \002(\005\022\025\n\rphdp"
    "ep_peplen\030\003 \002(\005\022\031\n\021phdpep_cleavedpep\030\004 \002"
    "(\005\"\323\001\n\016phd_parameters\022\035\n\025phdparam_precut"
    "_amino\030\001 \002(\t\022\036\n\026phdparam_postcut_amino\030\002"
    " \002(\t\022\037\n\027phdparam_prenocut_amino\030\003 \002(\t\022 \n"
    "\030phdparam_postnocut_amino\030\004 \002(\t\022 \n\030phdpa"
    "ram_missed_cleavage\030\005 \002(\005\022\035\n\025phdparam_se"
    "mi_tryptic\030\006 \002(\005\"\222\002\n\nphd_header\022\026\n\016phdhd"
    "r_version\030\001 \002(\005\022&\n\036phdhdr_protein_source"
    "_filename\030\002 \002(\t\022)\n!phdhdr_protein_source"
    "_file_digest\030\003 \002(\t\022\033\n\023phdhdr_num_protein"
    "s\030\004 \002(\005\022\035\n\025phdhdr_hash_file_name\030\005 \002(\t\022\037"
    "\n\027phdhdr_hash_file_digest\030\006 \002(\t\022<\n\rphdhd"
    "r_params\030\007 \002(\0132%.peptide_hash_database.p"
    "hd_parameters\"l\n\020phd_peptide_mass\022\025\n\rphd"
    "pmass_mass\030\001 \002(\005\022A\n\025phdpmass_peptide_lis"
    "t\030\002 \003(\0132\".peptide_hash_database.phd_pept"
    "ide\"\253\001\n\010phd_file\0221\n\006phdhdr\030\001 \001(\0132!.pepti"
    "de_hash_database.phd_header\0222\n\006phdpro\030\002 "
    "\003(\0132\".peptide_hash_database.phd_protein\022"
    "8\n\007phdpepm\030\003 \003(\0132\'.peptide_hash_database"
    ".phd_peptide_mass", 1017);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protein_pep_hash.proto", &protobuf_RegisterTypes);
  phd_protein::default_instance_ = new phd_protein();
  phd_peptide::default_instance_ = new phd_peptide();
  phd_parameters::default_instance_ = new phd_parameters();
  phd_header::default_instance_ = new phd_header();
  phd_peptide_mass::default_instance_ = new phd_peptide_mass();
  phd_file::default_instance_ = new phd_file();
  phd_protein::default_instance_->InitAsDefaultInstance();
  phd_peptide::default_instance_->InitAsDefaultInstance();
  phd_parameters::default_instance_->InitAsDefaultInstance();
  phd_header::default_instance_->InitAsDefaultInstance();
  phd_peptide_mass::default_instance_->InitAsDefaultInstance();
  phd_file::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protein_5fpep_5fhash_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protein_5fpep_5fhash_2eproto {
  StaticDescriptorInitializer_protein_5fpep_5fhash_2eproto() {
    protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  }
} static_descriptor_initializer_protein_5fpep_5fhash_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int phd_protein::kPhdproNameFieldNumber;
const int phd_protein::kPhdproIdFieldNumber;
const int phd_protein::kPhdproPepseqFieldNumber;
#endif  // !_MSC_VER

phd_protein::phd_protein()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_protein::InitAsDefaultInstance() {
}

phd_protein::phd_protein(const phd_protein& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_protein::SharedCtor() {
  _cached_size_ = 0;
  phdpro_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdpro_id_ = 0;
  phdpro_pepseq_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_protein::~phd_protein() {
  SharedDtor();
}

void phd_protein::SharedDtor() {
  if (phdpro_name_ != &::google::protobuf::internal::kEmptyString) {
    delete phdpro_name_;
  }
  if (phdpro_pepseq_ != &::google::protobuf::internal::kEmptyString) {
    delete phdpro_pepseq_;
  }
  if (this != default_instance_) {
  }
}

void phd_protein::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_protein::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_protein_descriptor_;
}

const phd_protein& phd_protein::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_protein* phd_protein::default_instance_ = NULL;

phd_protein* phd_protein::New() const {
  return new phd_protein;
}

void phd_protein::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_phdpro_name()) {
      if (phdpro_name_ != &::google::protobuf::internal::kEmptyString) {
        phdpro_name_->clear();
      }
    }
    phdpro_id_ = 0;
    if (has_phdpro_pepseq()) {
      if (phdpro_pepseq_ != &::google::protobuf::internal::kEmptyString) {
        phdpro_pepseq_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_protein::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string phdpro_name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdpro_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdpro_name().data(), this->phdpro_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_phdpro_id;
        break;
      }

      // required int32 phdpro_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdpro_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpro_id_)));
          set_has_phdpro_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_phdpro_pepseq;
        break;
      }

      // required string phdpro_pepseq = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdpro_pepseq:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdpro_pepseq()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdpro_pepseq().data(), this->phdpro_pepseq().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_protein::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string phdpro_name = 1;
  if (has_phdpro_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdpro_name().data(), this->phdpro_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->phdpro_name(), output);
  }

  // required int32 phdpro_id = 2;
  if (has_phdpro_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->phdpro_id(), output);
  }

  // required string phdpro_pepseq = 3;
  if (has_phdpro_pepseq()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdpro_pepseq().data(), this->phdpro_pepseq().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->phdpro_pepseq(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_protein::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string phdpro_name = 1;
  if (has_phdpro_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdpro_name().data(), this->phdpro_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->phdpro_name(), target);
  }

  // required int32 phdpro_id = 2;
  if (has_phdpro_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->phdpro_id(), target);
  }

  // required string phdpro_pepseq = 3;
  if (has_phdpro_pepseq()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdpro_pepseq().data(), this->phdpro_pepseq().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->phdpro_pepseq(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_protein::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string phdpro_name = 1;
    if (has_phdpro_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdpro_name());
    }

    // required int32 phdpro_id = 2;
    if (has_phdpro_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpro_id());
    }

    // required string phdpro_pepseq = 3;
    if (has_phdpro_pepseq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdpro_pepseq());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_protein::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_protein* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_protein*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_protein::MergeFrom(const phd_protein& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdpro_name()) {
      set_phdpro_name(from.phdpro_name());
    }
    if (from.has_phdpro_id()) {
      set_phdpro_id(from.phdpro_id());
    }
    if (from.has_phdpro_pepseq()) {
      set_phdpro_pepseq(from.phdpro_pepseq());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_protein::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_protein::CopyFrom(const phd_protein& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_protein::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void phd_protein::Swap(phd_protein* other) {
  if (other != this) {
    std::swap(phdpro_name_, other->phdpro_name_);
    std::swap(phdpro_id_, other->phdpro_id_);
    std::swap(phdpro_pepseq_, other->phdpro_pepseq_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_protein::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_protein_descriptor_;
  metadata.reflection = phd_protein_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int phd_peptide::kPhdpepProteinIdFieldNumber;
const int phd_peptide::kPhdpepPepstartFieldNumber;
const int phd_peptide::kPhdpepPeplenFieldNumber;
const int phd_peptide::kPhdpepCleavedpepFieldNumber;
#endif  // !_MSC_VER

phd_peptide::phd_peptide()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_peptide::InitAsDefaultInstance() {
}

phd_peptide::phd_peptide(const phd_peptide& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_peptide::SharedCtor() {
  _cached_size_ = 0;
  phdpep_protein_id_ = 0;
  phdpep_pepstart_ = 0;
  phdpep_peplen_ = 0;
  phdpep_cleavedpep_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_peptide::~phd_peptide() {
  SharedDtor();
}

void phd_peptide::SharedDtor() {
  if (this != default_instance_) {
  }
}

void phd_peptide::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_peptide::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_peptide_descriptor_;
}

const phd_peptide& phd_peptide::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_peptide* phd_peptide::default_instance_ = NULL;

phd_peptide* phd_peptide::New() const {
  return new phd_peptide;
}

void phd_peptide::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    phdpep_protein_id_ = 0;
    phdpep_pepstart_ = 0;
    phdpep_peplen_ = 0;
    phdpep_cleavedpep_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_peptide::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 phdpep_protein_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpep_protein_id_)));
          set_has_phdpep_protein_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_phdpep_pepstart;
        break;
      }

      // required int32 phdpep_pepstart = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdpep_pepstart:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpep_pepstart_)));
          set_has_phdpep_pepstart();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_phdpep_peplen;
        break;
      }

      // required int32 phdpep_peplen = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdpep_peplen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpep_peplen_)));
          set_has_phdpep_peplen();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_phdpep_cleavedpep;
        break;
      }

      // required int32 phdpep_cleavedpep = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdpep_cleavedpep:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpep_cleavedpep_)));
          set_has_phdpep_cleavedpep();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_peptide::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 phdpep_protein_id = 1;
  if (has_phdpep_protein_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->phdpep_protein_id(), output);
  }

  // required int32 phdpep_pepstart = 2;
  if (has_phdpep_pepstart()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->phdpep_pepstart(), output);
  }

  // required int32 phdpep_peplen = 3;
  if (has_phdpep_peplen()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->phdpep_peplen(), output);
  }

  // required int32 phdpep_cleavedpep = 4;
  if (has_phdpep_cleavedpep()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->phdpep_cleavedpep(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_peptide::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 phdpep_protein_id = 1;
  if (has_phdpep_protein_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->phdpep_protein_id(), target);
  }

  // required int32 phdpep_pepstart = 2;
  if (has_phdpep_pepstart()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->phdpep_pepstart(), target);
  }

  // required int32 phdpep_peplen = 3;
  if (has_phdpep_peplen()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->phdpep_peplen(), target);
  }

  // required int32 phdpep_cleavedpep = 4;
  if (has_phdpep_cleavedpep()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->phdpep_cleavedpep(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_peptide::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 phdpep_protein_id = 1;
    if (has_phdpep_protein_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpep_protein_id());
    }

    // required int32 phdpep_pepstart = 2;
    if (has_phdpep_pepstart()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpep_pepstart());
    }

    // required int32 phdpep_peplen = 3;
    if (has_phdpep_peplen()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpep_peplen());
    }

    // required int32 phdpep_cleavedpep = 4;
    if (has_phdpep_cleavedpep()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpep_cleavedpep());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_peptide::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_peptide* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_peptide*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_peptide::MergeFrom(const phd_peptide& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdpep_protein_id()) {
      set_phdpep_protein_id(from.phdpep_protein_id());
    }
    if (from.has_phdpep_pepstart()) {
      set_phdpep_pepstart(from.phdpep_pepstart());
    }
    if (from.has_phdpep_peplen()) {
      set_phdpep_peplen(from.phdpep_peplen());
    }
    if (from.has_phdpep_cleavedpep()) {
      set_phdpep_cleavedpep(from.phdpep_cleavedpep());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_peptide::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_peptide::CopyFrom(const phd_peptide& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_peptide::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void phd_peptide::Swap(phd_peptide* other) {
  if (other != this) {
    std::swap(phdpep_protein_id_, other->phdpep_protein_id_);
    std::swap(phdpep_pepstart_, other->phdpep_pepstart_);
    std::swap(phdpep_peplen_, other->phdpep_peplen_);
    std::swap(phdpep_cleavedpep_, other->phdpep_cleavedpep_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_peptide::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_peptide_descriptor_;
  metadata.reflection = phd_peptide_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int phd_parameters::kPhdparamPrecutAminoFieldNumber;
const int phd_parameters::kPhdparamPostcutAminoFieldNumber;
const int phd_parameters::kPhdparamPrenocutAminoFieldNumber;
const int phd_parameters::kPhdparamPostnocutAminoFieldNumber;
const int phd_parameters::kPhdparamMissedCleavageFieldNumber;
const int phd_parameters::kPhdparamSemiTrypticFieldNumber;
#endif  // !_MSC_VER

phd_parameters::phd_parameters()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_parameters::InitAsDefaultInstance() {
}

phd_parameters::phd_parameters(const phd_parameters& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_parameters::SharedCtor() {
  _cached_size_ = 0;
  phdparam_precut_amino_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdparam_postcut_amino_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdparam_prenocut_amino_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdparam_postnocut_amino_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdparam_missed_cleavage_ = 0;
  phdparam_semi_tryptic_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_parameters::~phd_parameters() {
  SharedDtor();
}

void phd_parameters::SharedDtor() {
  if (phdparam_precut_amino_ != &::google::protobuf::internal::kEmptyString) {
    delete phdparam_precut_amino_;
  }
  if (phdparam_postcut_amino_ != &::google::protobuf::internal::kEmptyString) {
    delete phdparam_postcut_amino_;
  }
  if (phdparam_prenocut_amino_ != &::google::protobuf::internal::kEmptyString) {
    delete phdparam_prenocut_amino_;
  }
  if (phdparam_postnocut_amino_ != &::google::protobuf::internal::kEmptyString) {
    delete phdparam_postnocut_amino_;
  }
  if (this != default_instance_) {
  }
}

void phd_parameters::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_parameters::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_parameters_descriptor_;
}

const phd_parameters& phd_parameters::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_parameters* phd_parameters::default_instance_ = NULL;

phd_parameters* phd_parameters::New() const {
  return new phd_parameters;
}

void phd_parameters::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_phdparam_precut_amino()) {
      if (phdparam_precut_amino_ != &::google::protobuf::internal::kEmptyString) {
        phdparam_precut_amino_->clear();
      }
    }
    if (has_phdparam_postcut_amino()) {
      if (phdparam_postcut_amino_ != &::google::protobuf::internal::kEmptyString) {
        phdparam_postcut_amino_->clear();
      }
    }
    if (has_phdparam_prenocut_amino()) {
      if (phdparam_prenocut_amino_ != &::google::protobuf::internal::kEmptyString) {
        phdparam_prenocut_amino_->clear();
      }
    }
    if (has_phdparam_postnocut_amino()) {
      if (phdparam_postnocut_amino_ != &::google::protobuf::internal::kEmptyString) {
        phdparam_postnocut_amino_->clear();
      }
    }
    phdparam_missed_cleavage_ = 0;
    phdparam_semi_tryptic_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_parameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string phdparam_precut_amino = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdparam_precut_amino()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdparam_precut_amino().data(), this->phdparam_precut_amino().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdparam_postcut_amino;
        break;
      }

      // required string phdparam_postcut_amino = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdparam_postcut_amino:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdparam_postcut_amino()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdparam_postcut_amino().data(), this->phdparam_postcut_amino().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_phdparam_prenocut_amino;
        break;
      }

      // required string phdparam_prenocut_amino = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdparam_prenocut_amino:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdparam_prenocut_amino()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdparam_prenocut_amino().data(), this->phdparam_prenocut_amino().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_phdparam_postnocut_amino;
        break;
      }

      // required string phdparam_postnocut_amino = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdparam_postnocut_amino:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdparam_postnocut_amino()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdparam_postnocut_amino().data(), this->phdparam_postnocut_amino().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_phdparam_missed_cleavage;
        break;
      }

      // required int32 phdparam_missed_cleavage = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdparam_missed_cleavage:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdparam_missed_cleavage_)));
          set_has_phdparam_missed_cleavage();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_phdparam_semi_tryptic;
        break;
      }

      // required int32 phdparam_semi_tryptic = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdparam_semi_tryptic:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdparam_semi_tryptic_)));
          set_has_phdparam_semi_tryptic();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_parameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string phdparam_precut_amino = 1;
  if (has_phdparam_precut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_precut_amino().data(), this->phdparam_precut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->phdparam_precut_amino(), output);
  }

  // required string phdparam_postcut_amino = 2;
  if (has_phdparam_postcut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_postcut_amino().data(), this->phdparam_postcut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->phdparam_postcut_amino(), output);
  }

  // required string phdparam_prenocut_amino = 3;
  if (has_phdparam_prenocut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_prenocut_amino().data(), this->phdparam_prenocut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->phdparam_prenocut_amino(), output);
  }

  // required string phdparam_postnocut_amino = 4;
  if (has_phdparam_postnocut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_postnocut_amino().data(), this->phdparam_postnocut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->phdparam_postnocut_amino(), output);
  }

  // required int32 phdparam_missed_cleavage = 5;
  if (has_phdparam_missed_cleavage()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->phdparam_missed_cleavage(), output);
  }

  // required int32 phdparam_semi_tryptic = 6;
  if (has_phdparam_semi_tryptic()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->phdparam_semi_tryptic(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_parameters::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string phdparam_precut_amino = 1;
  if (has_phdparam_precut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_precut_amino().data(), this->phdparam_precut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->phdparam_precut_amino(), target);
  }

  // required string phdparam_postcut_amino = 2;
  if (has_phdparam_postcut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_postcut_amino().data(), this->phdparam_postcut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->phdparam_postcut_amino(), target);
  }

  // required string phdparam_prenocut_amino = 3;
  if (has_phdparam_prenocut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_prenocut_amino().data(), this->phdparam_prenocut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->phdparam_prenocut_amino(), target);
  }

  // required string phdparam_postnocut_amino = 4;
  if (has_phdparam_postnocut_amino()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdparam_postnocut_amino().data(), this->phdparam_postnocut_amino().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->phdparam_postnocut_amino(), target);
  }

  // required int32 phdparam_missed_cleavage = 5;
  if (has_phdparam_missed_cleavage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->phdparam_missed_cleavage(), target);
  }

  // required int32 phdparam_semi_tryptic = 6;
  if (has_phdparam_semi_tryptic()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->phdparam_semi_tryptic(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_parameters::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string phdparam_precut_amino = 1;
    if (has_phdparam_precut_amino()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdparam_precut_amino());
    }

    // required string phdparam_postcut_amino = 2;
    if (has_phdparam_postcut_amino()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdparam_postcut_amino());
    }

    // required string phdparam_prenocut_amino = 3;
    if (has_phdparam_prenocut_amino()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdparam_prenocut_amino());
    }

    // required string phdparam_postnocut_amino = 4;
    if (has_phdparam_postnocut_amino()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdparam_postnocut_amino());
    }

    // required int32 phdparam_missed_cleavage = 5;
    if (has_phdparam_missed_cleavage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdparam_missed_cleavage());
    }

    // required int32 phdparam_semi_tryptic = 6;
    if (has_phdparam_semi_tryptic()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdparam_semi_tryptic());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_parameters::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_parameters* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_parameters*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_parameters::MergeFrom(const phd_parameters& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdparam_precut_amino()) {
      set_phdparam_precut_amino(from.phdparam_precut_amino());
    }
    if (from.has_phdparam_postcut_amino()) {
      set_phdparam_postcut_amino(from.phdparam_postcut_amino());
    }
    if (from.has_phdparam_prenocut_amino()) {
      set_phdparam_prenocut_amino(from.phdparam_prenocut_amino());
    }
    if (from.has_phdparam_postnocut_amino()) {
      set_phdparam_postnocut_amino(from.phdparam_postnocut_amino());
    }
    if (from.has_phdparam_missed_cleavage()) {
      set_phdparam_missed_cleavage(from.phdparam_missed_cleavage());
    }
    if (from.has_phdparam_semi_tryptic()) {
      set_phdparam_semi_tryptic(from.phdparam_semi_tryptic());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_parameters::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_parameters::CopyFrom(const phd_parameters& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_parameters::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  return true;
}

void phd_parameters::Swap(phd_parameters* other) {
  if (other != this) {
    std::swap(phdparam_precut_amino_, other->phdparam_precut_amino_);
    std::swap(phdparam_postcut_amino_, other->phdparam_postcut_amino_);
    std::swap(phdparam_prenocut_amino_, other->phdparam_prenocut_amino_);
    std::swap(phdparam_postnocut_amino_, other->phdparam_postnocut_amino_);
    std::swap(phdparam_missed_cleavage_, other->phdparam_missed_cleavage_);
    std::swap(phdparam_semi_tryptic_, other->phdparam_semi_tryptic_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_parameters::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_parameters_descriptor_;
  metadata.reflection = phd_parameters_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int phd_header::kPhdhdrVersionFieldNumber;
const int phd_header::kPhdhdrProteinSourceFilenameFieldNumber;
const int phd_header::kPhdhdrProteinSourceFileDigestFieldNumber;
const int phd_header::kPhdhdrNumProteinsFieldNumber;
const int phd_header::kPhdhdrHashFileNameFieldNumber;
const int phd_header::kPhdhdrHashFileDigestFieldNumber;
const int phd_header::kPhdhdrParamsFieldNumber;
#endif  // !_MSC_VER

phd_header::phd_header()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_header::InitAsDefaultInstance() {
  phdhdr_params_ = const_cast< ::peptide_hash_database::phd_parameters*>(&::peptide_hash_database::phd_parameters::default_instance());
}

phd_header::phd_header(const phd_header& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_header::SharedCtor() {
  _cached_size_ = 0;
  phdhdr_version_ = 0;
  phdhdr_protein_source_filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdhdr_protein_source_file_digest_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdhdr_num_proteins_ = 0;
  phdhdr_hash_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdhdr_hash_file_digest_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  phdhdr_params_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_header::~phd_header() {
  SharedDtor();
}

void phd_header::SharedDtor() {
  if (phdhdr_protein_source_filename_ != &::google::protobuf::internal::kEmptyString) {
    delete phdhdr_protein_source_filename_;
  }
  if (phdhdr_protein_source_file_digest_ != &::google::protobuf::internal::kEmptyString) {
    delete phdhdr_protein_source_file_digest_;
  }
  if (phdhdr_hash_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete phdhdr_hash_file_name_;
  }
  if (phdhdr_hash_file_digest_ != &::google::protobuf::internal::kEmptyString) {
    delete phdhdr_hash_file_digest_;
  }
  if (this != default_instance_) {
    delete phdhdr_params_;
  }
}

void phd_header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_header::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_header_descriptor_;
}

const phd_header& phd_header::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_header* phd_header::default_instance_ = NULL;

phd_header* phd_header::New() const {
  return new phd_header;
}

void phd_header::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    phdhdr_version_ = 0;
    if (has_phdhdr_protein_source_filename()) {
      if (phdhdr_protein_source_filename_ != &::google::protobuf::internal::kEmptyString) {
        phdhdr_protein_source_filename_->clear();
      }
    }
    if (has_phdhdr_protein_source_file_digest()) {
      if (phdhdr_protein_source_file_digest_ != &::google::protobuf::internal::kEmptyString) {
        phdhdr_protein_source_file_digest_->clear();
      }
    }
    phdhdr_num_proteins_ = 0;
    if (has_phdhdr_hash_file_name()) {
      if (phdhdr_hash_file_name_ != &::google::protobuf::internal::kEmptyString) {
        phdhdr_hash_file_name_->clear();
      }
    }
    if (has_phdhdr_hash_file_digest()) {
      if (phdhdr_hash_file_digest_ != &::google::protobuf::internal::kEmptyString) {
        phdhdr_hash_file_digest_->clear();
      }
    }
    if (has_phdhdr_params()) {
      if (phdhdr_params_ != NULL) phdhdr_params_->::peptide_hash_database::phd_parameters::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 phdhdr_version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdhdr_version_)));
          set_has_phdhdr_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdhdr_protein_source_filename;
        break;
      }

      // required string phdhdr_protein_source_filename = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdhdr_protein_source_filename:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdhdr_protein_source_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdhdr_protein_source_filename().data(), this->phdhdr_protein_source_filename().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_phdhdr_protein_source_file_digest;
        break;
      }

      // required string phdhdr_protein_source_file_digest = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdhdr_protein_source_file_digest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdhdr_protein_source_file_digest()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdhdr_protein_source_file_digest().data(), this->phdhdr_protein_source_file_digest().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_phdhdr_num_proteins;
        break;
      }

      // required int32 phdhdr_num_proteins = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_phdhdr_num_proteins:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdhdr_num_proteins_)));
          set_has_phdhdr_num_proteins();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_phdhdr_hash_file_name;
        break;
      }

      // required string phdhdr_hash_file_name = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdhdr_hash_file_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdhdr_hash_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdhdr_hash_file_name().data(), this->phdhdr_hash_file_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_phdhdr_hash_file_digest;
        break;
      }

      // required string phdhdr_hash_file_digest = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdhdr_hash_file_digest:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phdhdr_hash_file_digest()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->phdhdr_hash_file_digest().data(), this->phdhdr_hash_file_digest().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_phdhdr_params;
        break;
      }

      // required .peptide_hash_database.phd_parameters phdhdr_params = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdhdr_params:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_phdhdr_params()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 phdhdr_version = 1;
  if (has_phdhdr_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->phdhdr_version(), output);
  }

  // required string phdhdr_protein_source_filename = 2;
  if (has_phdhdr_protein_source_filename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_protein_source_filename().data(), this->phdhdr_protein_source_filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->phdhdr_protein_source_filename(), output);
  }

  // required string phdhdr_protein_source_file_digest = 3;
  if (has_phdhdr_protein_source_file_digest()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_protein_source_file_digest().data(), this->phdhdr_protein_source_file_digest().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->phdhdr_protein_source_file_digest(), output);
  }

  // required int32 phdhdr_num_proteins = 4;
  if (has_phdhdr_num_proteins()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->phdhdr_num_proteins(), output);
  }

  // required string phdhdr_hash_file_name = 5;
  if (has_phdhdr_hash_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_hash_file_name().data(), this->phdhdr_hash_file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->phdhdr_hash_file_name(), output);
  }

  // required string phdhdr_hash_file_digest = 6;
  if (has_phdhdr_hash_file_digest()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_hash_file_digest().data(), this->phdhdr_hash_file_digest().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->phdhdr_hash_file_digest(), output);
  }

  // required .peptide_hash_database.phd_parameters phdhdr_params = 7;
  if (has_phdhdr_params()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->phdhdr_params(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_header::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 phdhdr_version = 1;
  if (has_phdhdr_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->phdhdr_version(), target);
  }

  // required string phdhdr_protein_source_filename = 2;
  if (has_phdhdr_protein_source_filename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_protein_source_filename().data(), this->phdhdr_protein_source_filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->phdhdr_protein_source_filename(), target);
  }

  // required string phdhdr_protein_source_file_digest = 3;
  if (has_phdhdr_protein_source_file_digest()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_protein_source_file_digest().data(), this->phdhdr_protein_source_file_digest().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->phdhdr_protein_source_file_digest(), target);
  }

  // required int32 phdhdr_num_proteins = 4;
  if (has_phdhdr_num_proteins()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->phdhdr_num_proteins(), target);
  }

  // required string phdhdr_hash_file_name = 5;
  if (has_phdhdr_hash_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_hash_file_name().data(), this->phdhdr_hash_file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->phdhdr_hash_file_name(), target);
  }

  // required string phdhdr_hash_file_digest = 6;
  if (has_phdhdr_hash_file_digest()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->phdhdr_hash_file_digest().data(), this->phdhdr_hash_file_digest().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->phdhdr_hash_file_digest(), target);
  }

  // required .peptide_hash_database.phd_parameters phdhdr_params = 7;
  if (has_phdhdr_params()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->phdhdr_params(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_header::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 phdhdr_version = 1;
    if (has_phdhdr_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdhdr_version());
    }

    // required string phdhdr_protein_source_filename = 2;
    if (has_phdhdr_protein_source_filename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdhdr_protein_source_filename());
    }

    // required string phdhdr_protein_source_file_digest = 3;
    if (has_phdhdr_protein_source_file_digest()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdhdr_protein_source_file_digest());
    }

    // required int32 phdhdr_num_proteins = 4;
    if (has_phdhdr_num_proteins()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdhdr_num_proteins());
    }

    // required string phdhdr_hash_file_name = 5;
    if (has_phdhdr_hash_file_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdhdr_hash_file_name());
    }

    // required string phdhdr_hash_file_digest = 6;
    if (has_phdhdr_hash_file_digest()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phdhdr_hash_file_digest());
    }

    // required .peptide_hash_database.phd_parameters phdhdr_params = 7;
    if (has_phdhdr_params()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->phdhdr_params());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_header::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_header* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_header*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_header::MergeFrom(const phd_header& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdhdr_version()) {
      set_phdhdr_version(from.phdhdr_version());
    }
    if (from.has_phdhdr_protein_source_filename()) {
      set_phdhdr_protein_source_filename(from.phdhdr_protein_source_filename());
    }
    if (from.has_phdhdr_protein_source_file_digest()) {
      set_phdhdr_protein_source_file_digest(from.phdhdr_protein_source_file_digest());
    }
    if (from.has_phdhdr_num_proteins()) {
      set_phdhdr_num_proteins(from.phdhdr_num_proteins());
    }
    if (from.has_phdhdr_hash_file_name()) {
      set_phdhdr_hash_file_name(from.phdhdr_hash_file_name());
    }
    if (from.has_phdhdr_hash_file_digest()) {
      set_phdhdr_hash_file_digest(from.phdhdr_hash_file_digest());
    }
    if (from.has_phdhdr_params()) {
      mutable_phdhdr_params()->::peptide_hash_database::phd_parameters::MergeFrom(from.phdhdr_params());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_header::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_header::CopyFrom(const phd_header& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_header::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  if (has_phdhdr_params()) {
    if (!this->phdhdr_params().IsInitialized()) return false;
  }
  return true;
}

void phd_header::Swap(phd_header* other) {
  if (other != this) {
    std::swap(phdhdr_version_, other->phdhdr_version_);
    std::swap(phdhdr_protein_source_filename_, other->phdhdr_protein_source_filename_);
    std::swap(phdhdr_protein_source_file_digest_, other->phdhdr_protein_source_file_digest_);
    std::swap(phdhdr_num_proteins_, other->phdhdr_num_proteins_);
    std::swap(phdhdr_hash_file_name_, other->phdhdr_hash_file_name_);
    std::swap(phdhdr_hash_file_digest_, other->phdhdr_hash_file_digest_);
    std::swap(phdhdr_params_, other->phdhdr_params_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_header::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_header_descriptor_;
  metadata.reflection = phd_header_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int phd_peptide_mass::kPhdpmassMassFieldNumber;
const int phd_peptide_mass::kPhdpmassPeptideListFieldNumber;
#endif  // !_MSC_VER

phd_peptide_mass::phd_peptide_mass()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_peptide_mass::InitAsDefaultInstance() {
}

phd_peptide_mass::phd_peptide_mass(const phd_peptide_mass& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_peptide_mass::SharedCtor() {
  _cached_size_ = 0;
  phdpmass_mass_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_peptide_mass::~phd_peptide_mass() {
  SharedDtor();
}

void phd_peptide_mass::SharedDtor() {
  if (this != default_instance_) {
  }
}

void phd_peptide_mass::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_peptide_mass::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_peptide_mass_descriptor_;
}

const phd_peptide_mass& phd_peptide_mass::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_peptide_mass* phd_peptide_mass::default_instance_ = NULL;

phd_peptide_mass* phd_peptide_mass::New() const {
  return new phd_peptide_mass;
}

void phd_peptide_mass::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    phdpmass_mass_ = 0;
  }
  phdpmass_peptide_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_peptide_mass::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 phdpmass_mass = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &phdpmass_mass_)));
          set_has_phdpmass_mass();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdpmass_peptide_list;
        break;
      }

      // repeated .peptide_hash_database.phd_peptide phdpmass_peptide_list = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdpmass_peptide_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_phdpmass_peptide_list()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdpmass_peptide_list;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_peptide_mass::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 phdpmass_mass = 1;
  if (has_phdpmass_mass()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->phdpmass_mass(), output);
  }

  // repeated .peptide_hash_database.phd_peptide phdpmass_peptide_list = 2;
  for (int i = 0; i < this->phdpmass_peptide_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->phdpmass_peptide_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_peptide_mass::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 phdpmass_mass = 1;
  if (has_phdpmass_mass()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->phdpmass_mass(), target);
  }

  // repeated .peptide_hash_database.phd_peptide phdpmass_peptide_list = 2;
  for (int i = 0; i < this->phdpmass_peptide_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->phdpmass_peptide_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_peptide_mass::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 phdpmass_mass = 1;
    if (has_phdpmass_mass()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->phdpmass_mass());
    }

  }
  // repeated .peptide_hash_database.phd_peptide phdpmass_peptide_list = 2;
  total_size += 1 * this->phdpmass_peptide_list_size();
  for (int i = 0; i < this->phdpmass_peptide_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->phdpmass_peptide_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_peptide_mass::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_peptide_mass* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_peptide_mass*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_peptide_mass::MergeFrom(const phd_peptide_mass& from) {
  GOOGLE_CHECK_NE(&from, this);
  phdpmass_peptide_list_.MergeFrom(from.phdpmass_peptide_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdpmass_mass()) {
      set_phdpmass_mass(from.phdpmass_mass());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_peptide_mass::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_peptide_mass::CopyFrom(const phd_peptide_mass& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_peptide_mass::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < phdpmass_peptide_list_size(); i++) {
    if (!this->phdpmass_peptide_list(i).IsInitialized()) return false;
  }
  return true;
}

void phd_peptide_mass::Swap(phd_peptide_mass* other) {
  if (other != this) {
    std::swap(phdpmass_mass_, other->phdpmass_mass_);
    phdpmass_peptide_list_.Swap(&other->phdpmass_peptide_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_peptide_mass::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_peptide_mass_descriptor_;
  metadata.reflection = phd_peptide_mass_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int phd_file::kPhdhdrFieldNumber;
const int phd_file::kPhdproFieldNumber;
const int phd_file::kPhdpepmFieldNumber;
#endif  // !_MSC_VER

phd_file::phd_file()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void phd_file::InitAsDefaultInstance() {
  phdhdr_ = const_cast< ::peptide_hash_database::phd_header*>(&::peptide_hash_database::phd_header::default_instance());
}

phd_file::phd_file(const phd_file& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void phd_file::SharedCtor() {
  _cached_size_ = 0;
  phdhdr_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

phd_file::~phd_file() {
  SharedDtor();
}

void phd_file::SharedDtor() {
  if (this != default_instance_) {
    delete phdhdr_;
  }
}

void phd_file::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* phd_file::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return phd_file_descriptor_;
}

const phd_file& phd_file::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protein_5fpep_5fhash_2eproto();
  return *default_instance_;
}

phd_file* phd_file::default_instance_ = NULL;

phd_file* phd_file::New() const {
  return new phd_file;
}

void phd_file::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_phdhdr()) {
      if (phdhdr_ != NULL) phdhdr_->::peptide_hash_database::phd_header::Clear();
    }
  }
  phdpro_.Clear();
  phdpepm_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool phd_file::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .peptide_hash_database.phd_header phdhdr = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_phdhdr()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdpro;
        break;
      }

      // repeated .peptide_hash_database.phd_protein phdpro = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdpro:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_phdpro()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_phdpro;
        if (input->ExpectTag(26)) goto parse_phdpepm;
        break;
      }

      // repeated .peptide_hash_database.phd_peptide_mass phdpepm = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_phdpepm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_phdpepm()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_phdpepm;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void phd_file::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .peptide_hash_database.phd_header phdhdr = 1;
  if (has_phdhdr()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->phdhdr(), output);
  }

  // repeated .peptide_hash_database.phd_protein phdpro = 2;
  for (int i = 0; i < this->phdpro_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->phdpro(i), output);
  }

  // repeated .peptide_hash_database.phd_peptide_mass phdpepm = 3;
  for (int i = 0; i < this->phdpepm_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->phdpepm(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* phd_file::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .peptide_hash_database.phd_header phdhdr = 1;
  if (has_phdhdr()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->phdhdr(), target);
  }

  // repeated .peptide_hash_database.phd_protein phdpro = 2;
  for (int i = 0; i < this->phdpro_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->phdpro(i), target);
  }

  // repeated .peptide_hash_database.phd_peptide_mass phdpepm = 3;
  for (int i = 0; i < this->phdpepm_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->phdpepm(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int phd_file::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .peptide_hash_database.phd_header phdhdr = 1;
    if (has_phdhdr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->phdhdr());
    }

  }
  // repeated .peptide_hash_database.phd_protein phdpro = 2;
  total_size += 1 * this->phdpro_size();
  for (int i = 0; i < this->phdpro_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->phdpro(i));
  }

  // repeated .peptide_hash_database.phd_peptide_mass phdpepm = 3;
  total_size += 1 * this->phdpepm_size();
  for (int i = 0; i < this->phdpepm_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->phdpepm(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void phd_file::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const phd_file* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const phd_file*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void phd_file::MergeFrom(const phd_file& from) {
  GOOGLE_CHECK_NE(&from, this);
  phdpro_.MergeFrom(from.phdpro_);
  phdpepm_.MergeFrom(from.phdpepm_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_phdhdr()) {
      mutable_phdhdr()->::peptide_hash_database::phd_header::MergeFrom(from.phdhdr());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void phd_file::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void phd_file::CopyFrom(const phd_file& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool phd_file::IsInitialized() const {

  if (has_phdhdr()) {
    if (!this->phdhdr().IsInitialized()) return false;
  }
  for (int i = 0; i < phdpro_size(); i++) {
    if (!this->phdpro(i).IsInitialized()) return false;
  }
  for (int i = 0; i < phdpepm_size(); i++) {
    if (!this->phdpepm(i).IsInitialized()) return false;
  }
  return true;
}

void phd_file::Swap(phd_file* other) {
  if (other != this) {
    std::swap(phdhdr_, other->phdhdr_);
    phdpro_.Swap(&other->phdpro_);
    phdpepm_.Swap(&other->phdpepm_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata phd_file::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = phd_file_descriptor_;
  metadata.reflection = phd_file_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace peptide_hash_database

// @@protoc_insertion_point(global_scope)
